---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jgroups-k8s-service-account

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jgroups-k8s-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: jgroups-k8s-kubeping-api-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jgroups-k8s-cluster-role
subjects:
  - kind: ServiceAccount
    name: jgroups-k8s-service-account
    namespace: jgroups-k8s
