---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jgroups-k8s-service-account
  namespace: jgroups-k8s

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jgroups-k8s-role
  namespace: jgroups-k8s
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: jgroups-k8s-kubeping-api-access
  namespace: jgroups-k8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jgroups-k8s-role
subjects:
  - kind: ServiceAccount
    name: jgroups-k8s-service-account
    namespace: jgroups-k8s
