apiVersion: v1
kind: Service
metadata:
  name: jgroups-k8s
  namespace: jgroups-k8s
spec:
  selector:
    app: jgroups-k8s
  ports:
    - name: "http"
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: "jgroups"
      protocol: TCP
      port: 7800
      targetPort: 7800
