---
server:
  port: 9000

jgroups-k8s:
  config-path: "/jgroups/udp.xml"

---
spring:
  profiles: dns-ping

jgroups-k8s:
  config-path: "/jgroups/dns_ping.xml"

---
spring:
  profiles: kube-ping

jgroups-k8s:
  config-path: "/jgroups/kube_ping.xml"
